import { createRemoteJWKSet, jwtVerify, decodeProtectedHeader, decodeJwt } from 'jose';
import type { Request, Response, NextFunction } from 'express';
import { OathMeshError, type VerifierConfig, type VerifiedCallerContext } from './types';

// Extend Express Request
declare global {
  namespace Express {
    interface Request {
      oathmeshContext?: VerifiedCallerContext;
    }
  }
}

/**
 * Creates an Express middleware that verifies OathMesh tokens.
 *
 * Performs a subset of the 14-step verification pipeline:
 * - Extracts token from `Authorization: OathMesh <token>` header
 * - Validates header (typ, alg)
 * - Verifies signature against issuer's JWKS
 * - Checks audience, expiry, required claims
 * - Populates `req.oathmeshContext` on success
 *
 * @param config - Verifier configuration (audience + trusted issuers)
 * @returns Express middleware function
 */
export function verifyToken(config: VerifierConfig) {
  const { audience, trustedIssuers } = config;

  // Build JWKS clients for each trusted issuer
  const jwksMap = new Map<string, ReturnType<typeof createRemoteJWKSet>>();
  for (const issuer of trustedIssuers) {
    const url = new URL('/.well-known/jwks.json', issuer);
    jwksMap.set(issuer, createRemoteJWKSet(url, { cacheMaxAge: 300_000 }));
  }

  return async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    const authHeader = req.headers.authorization;

    // Step 01: Check Authorization header presence and format
    if (!authHeader || !authHeader.startsWith('OathMesh ')) {
      sendError(res, new OathMeshError(
        'claim_missing:token',
        'missing or invalid Authorization header',
        "provide a token in the format 'Authorization: OathMesh <token>'"
      ));
      return;
    }

    const token = authHeader.slice('OathMesh '.length);

    try {
      // Step 02: Decode and validate header
      const header = decodeProtectedHeader(token);
      if (header.typ !== 'om+jwt') {
        throw new OathMeshError('algorithm_not_allowed', 'invalid token type', 'token typ must be om+jwt');
      }
      if (header.alg === 'none') {
        throw new OathMeshError('algorithm_not_allowed', 'algorithm "none" is not allowed', 'use EdDSA or ES256');
      }

      // Step 03-04: Extract issuer and check trust
      const claims = decodeJwt(token);
      const iss = claims.iss;
      if (!iss || !trustedIssuers.includes(iss)) {
        throw new OathMeshError('issuer_untrusted', `issuer "${iss}" is not trusted`, 'add the issuer to your trustedIssuers list');
      }

      // Step 05-06: Load JWKS and verify signature
      const jwks = jwksMap.get(iss);
      if (!jwks) {
        throw new OathMeshError('issuer_untrusted', 'no JWKS available for issuer', 'ensure the issuer is in trustedIssuers');
      }

      const { payload } = await jwtVerify(token, jwks, {
        audience,
        issuer: iss,
        clockTolerance: 10,
      });

      // Step 11: Verify required claims
      if (!payload.sub) throw new OathMeshError('claim_missing:sub', 'missing sub claim', 'include sub when minting');
      if (!payload.act) throw new OathMeshError('claim_missing:act', 'missing act claim', 'include act when minting');
      if (!payload.jti) throw new OathMeshError('claim_missing:jti', 'missing jti claim', 'jti is auto-generated by the issuer');

      // Build verified context
      const context: VerifiedCallerContext = {
        principal: {
          issuer: iss,
          subject: payload.sub as string,
        },
        action: payload.act as string,
        tokenId: payload.jti as string,
        environment: (payload.env as string) || '',
        scope: payload.scope as string[] | undefined,
        reason: payload.reason as string | undefined,
        source: payload.src as VerifiedCallerContext['source'],
      };

      req.oathmeshContext = context;
      next();
    } catch (err) {
      if (err instanceof OathMeshError) {
        sendError(res, err);
        return;
      }

      // Map jose errors to OathMesh taxonomy
      const joseErr = err as Error;
      if (joseErr.message?.includes('expired')) {
        sendError(res, new OathMeshError('token_expired', 'token expired', 'mint a new token'));
      } else if (joseErr.message?.includes('audience')) {
        sendError(res, new OathMeshError('audience_mismatch', 'wrong audience', `mint with aud set to ${audience}`));
      } else if (joseErr.message?.includes('signature')) {
        sendError(res, new OathMeshError('signature_invalid', 'signature verification failed', 'check issuer key'));
      } else {
        sendError(res, new OathMeshError('verification_failed', joseErr.message || 'verification failed', 'check token format'));
      }
    }
  };
}

function sendError(res: Response, err: OathMeshError): void {
  res.status(401).json({
    error: err.code,
    message: err.message,
    fix: err.fix,
  });
}
