/**
 * Core OathMesh token verification — framework-agnostic.
 *
 * This module contains the pure verification logic shared by all framework
 * adapters (Express, Next.js App Router, Next.js Pages Router, Edge Middleware).
 * It has no dependency on any HTTP framework.
 */

import { createRemoteJWKSet, jwtVerify, decodeProtectedHeader, decodeJwt } from 'jose';
import { OathMeshError, type VerifierConfig, type VerifiedCallerContext, type PolicyInput } from './types';

/**
 * Module-level JWKS cache. Keys are issuer URLs, values are jose JWKS functions.
 * Shared across all verifier instances within the same process to avoid
 * redundant JWKS fetches in serverless (Next.js) environments where
 * module scope persists across requests.
 */
const globalJWKSCache = new Map<string, ReturnType<typeof createRemoteJWKSet>>();

function getJWKS(issuer: string): ReturnType<typeof createRemoteJWKSet> {
  let jwks = globalJWKSCache.get(issuer);
  if (!jwks) {
    const url = new URL('/.well-known/jwks.json', issuer);
    jwks = createRemoteJWKSet(url, { cacheMaxAge: 300_000 });
    globalJWKSCache.set(issuer, jwks);
  }
  return jwks;
}

/**
 * Extract the raw token string from an Authorization header value.
 *
 * Accepts:
 *   - `OathMesh <token>` (canonical)
 *   - `Bearer <token>` (compatibility — only when the token contains om+jwt typ)
 *
 * @returns The raw token string, or null if the header is missing/invalid.
 */
export function extractToken(authHeader: string | null | undefined): string | null {
  if (!authHeader) return null;
  if (authHeader.startsWith('OathMesh ')) return authHeader.slice(9);
  if (authHeader.startsWith('Bearer ')) return authHeader.slice(7);
  return null;
}

/**
 * Verify an OathMesh token string and return the verified caller context.
 *
 * This is the core verification function. Framework adapters call this
 * and handle HTTP responses themselves.
 *
 * @param token - Raw token string (without "OathMesh " prefix)
 * @param config - Verifier configuration
 * @returns Verified caller context on success
 * @throws OathMeshError on any verification failure
 */
export async function verifyOathToken(
  token: string,
  config: VerifierConfig
): Promise<VerifiedCallerContext> {
  const { audience, trustedIssuers } = config;

  // Step 02: Decode and validate header
  let header: ReturnType<typeof decodeProtectedHeader>;
  try {
    header = decodeProtectedHeader(token);
  } catch {
    throw new OathMeshError('verification_failed', 'malformed token header', 'check token format');
  }

  if (header.typ !== 'om+jwt') {
    throw new OathMeshError(
      'algorithm_not_allowed',
      `invalid token type "${header.typ}"`,
      'token typ must be om+jwt'
    );
  }
  if (header.alg === 'none') {
    throw new OathMeshError(
      'algorithm_not_allowed',
      'algorithm "none" is rejected — this is a security redline',
      'use EdDSA or ES256'
    );
  }
  if (!['EdDSA', 'ES256'].includes(header.alg!)) {
    throw new OathMeshError(
      'algorithm_not_allowed',
      `algorithm "${header.alg}" is not allowed`,
      'use EdDSA (preferred) or ES256'
    );
  }

  // Step 03–04: Extract issuer and check trust
  let claims: ReturnType<typeof decodeJwt>;
  try {
    claims = decodeJwt(token);
  } catch {
    throw new OathMeshError('verification_failed', 'malformed token payload', 'check token format');
  }

  const iss = claims.iss;
  if (!iss) {
    throw new OathMeshError('claim_missing:iss', 'missing iss claim', 'include iss when minting');
  }
  if (!trustedIssuers.includes(iss)) {
    throw new OathMeshError(
      'issuer_untrusted',
      `issuer "${iss}" is not in the trusted issuers list`,
      'add the issuer URL to your trustedIssuers configuration'
    );
  }

  // Step 05–06: Load JWKS and verify signature
  const jwks = getJWKS(iss);

  let payload: Record<string, unknown>;
  try {
    const result = await jwtVerify(token, jwks, {
      audience,
      issuer: iss,
      clockTolerance: 10,
    });
    payload = result.payload as Record<string, unknown>;
  } catch (err) {
    throw mapJoseError(err as Error, audience);
  }

  // Step 11: Verify required claims
  if (!payload.sub) throw new OathMeshError('claim_missing:sub', 'missing sub claim', 'include sub when minting');
  if (!payload.act) throw new OathMeshError('claim_missing:act', 'missing act claim', 'include act when minting');
  if (!payload.jti) throw new OathMeshError('claim_missing:jti', 'missing jti claim', 'jti is auto-generated by the issuer');

  // Step 12b: Enforce rqh if RequireRequestBinding is set
  if (config.requireRequestBinding && !payload.rqh) {
    throw new OathMeshError(
      'binding_required',
      'token missing rqh (request hash) claim',
      'mint a token with rqh= sha256:<canonical-request> for write/mutate operations'
    );
  }

  // Step 13: Check replay cache (if configured)
  if (config.replayCache) {
    const jti = payload.jti as string;
    if (config.replayCache.check(jti)) {
      throw new OathMeshError(
        'replay_detected',
        `token ${jti} has already been used`,
        'each Oath Token can only be used once — mint a new token'
      );
    }
    config.replayCache.add(jti);
  }

  // Step 14: Evaluate policy (if configured)
  if (config.policyEvaluator) {
    const policyInput: PolicyInput = {
      iss,
      sub: payload.sub as string,
      aud: payload.aud as string,
      act: payload.act as string,
      scope: payload.scope as string[] | undefined,
      env: payload.env as string | undefined,
    };
    const decision = await config.policyEvaluator.evaluate(policyInput);
    if (decision.outcome === 'deny') {
      throw new OathMeshError(
        'policy_denied',
        decision.denyReason || 'policy evaluation denied',
        'check policy rules for this request'
      );
    }
  }

  // Build verified context
  return {
    principal: {
      issuer: iss,
      subject: payload.sub as string,
    },
    action: payload.act as string,
    tokenId: payload.jti as string,
    environment: (payload.env as string) || '',
    scope: payload.scope as string[] | undefined,
    reason: payload.reason as string | undefined,
    source: payload.src as VerifiedCallerContext['source'],
  };
}

/**
 * Map a jose library error to the OathMesh error taxonomy.
 */
function mapJoseError(err: Error, audience: string): OathMeshError {
  const msg = err.message || '';
  if (msg.includes('expired') || err.name === 'JWTExpired') {
    return new OathMeshError('token_expired', 'token has expired', 'mint a new token — Oath Tokens are short-lived');
  }
  if (msg.includes('audience') || err.name === 'JWTClaimValidationFailed') {
    if (msg.includes('audience')) {
      return new OathMeshError('audience_mismatch', 'token audience does not match', `mint with --aud ${audience}`);
    }
  }
  if (msg.includes('signature') || err.name === 'JWSSignatureVerificationFailed') {
    return new OathMeshError('signature_invalid', 'JWS signature verification failed', 'check that the token was signed by a trusted issuer');
  }
  if (msg.includes('issuer')) {
    return new OathMeshError('issuer_untrusted', 'issuer verification failed', 'check trustedIssuers configuration');
  }
  return new OathMeshError('verification_failed', msg || 'token verification failed', 'check token format and issuer availability');
}
